export enum RequestsActionTypes {
    LOAD_SERVER_REQUESTS = '@@mappings/LOAD_SERVER_REQUESTS',
    LOAD_SERVER_REQUESTS_REQUEST = '@@mappings/LOAD_SERVER_REQUESTS_REQUEST',
    LOAD_SERVER_REQUESTS_SUCCESS = '@@mappings/LOAD_SERVER_REQUESTS_SUCCESS',
}
